### ISSUE TITLE
import statements do not work w/ vendored packages, go modules.

### ISSUE THREAD

**Issue by james-lawrence** [traefik/yaegi#422] opened 2019-10-19 16:59 UTC
golangs package resolution is fairly complicated and the simplistic code in
```
func pkgDir(gopath, root, path string) (string, string, error) {
```
doesn't work well and misses edge cases. consider instead:

```
func pkgDir(ctx build.Context, rPath, pkg string) (string, error) {
	pkg, err := ctx.Import(path, ".", build.FindOnly)
        if err != nil {
           return "", err
        }
        return pkg.Dir, err
}
```

note: this doesn't work out of the box. I havent figured out what the other assumptions yaegi is making when resolving imports, but it at least resolves the directory of the package correctly in all cases. (including modules)

**Comment by mvertes** [comment] 2019-10-30 11:33
The `pkgDir` function has been designed and works for vendored packages and GOPATH packages. Go modules are not supported yet, and it may require another approach/design that we do not have yet.  

Let me know if you found some problems within the currently supported schemes (vendored + GOPATH).

**Comment by james-lawrence** [comment] 2019-11-02 11:19
well it doesn't work with vendored either in my use case, as I said the logic is far too simplistic.

**Comment by james-lawrence** [comment] 2019-11-22 01:23
@mvertes please see the above, it doesn't work for all vendor package setups.

**Comment by mpl** [comment] 2020-08-27 10:26
We should probably close this issue since no reproducible case of unsupported vendoring case has been provided.

**Comment by mvertes** [comment] 2020-10-15 10:20
Closing this issue. A new one can be opened if  necessary.

**Closed by mvertes** 2020-10-15 10:20 UTC
Labels: area/core, contributor/need-more-information, enhancement
