### ISSUE TITLE
Redeclaring imports

### ISSUE THREAD

**Issue by dfilipovic39** [traefik/yaegi#731] opened 2020-07-01 11:56 UTC
I used to load multiple scripts using **Eval** method in version 0.8.5. They had same package name and shared some same imports. Now I'm getting 'xxx redeclared in this block' (xxx being the imported package name).
Not sure why is this invalid now as this feature allowed me to split sources across multiple files.

**Comment by mvertes** [comment] 2020-07-05 16:04
Please could you provide a testable example of your use case so we can investigate further ?
Thank you.

**Comment by dfilipovic39** [comment] 2020-07-06 17:43
Sure, should have provided it in issue, sorry.
Lets say I have two script files loaded from filesystem - script1.go and script2.go. The source code has them inlined. The import statement seems to be a global symbol that cannot be redeclared as with version **v0.8.9** this snippet fails with error:
```
panic: 3:8: fmt redeclared in this block

goroutine 1 [running]:
main.main()
        /home/tarqe39/gomod/services/test/yaegi.go:31 +0x27b
```
**Code:**
```go
package main

import (
	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

const (
	script1 = `package subpkg

import "fmt"

func PrintA()  {
	fmt.Println("A")
}`

	script2 = `package subpkg

import "fmt"

func PrintB()  {
	fmt.Println("B")
}`
)

func main() {

	i := interp.New(interp.Options{})

	i.Use(stdlib.Symbols)

	_, err := i.Eval(script1)
	if err != nil {
		panic(err)
	}

	_, err = i.Eval(script2)
	if err != nil {
		panic(err)
	}
	_, err = i.Eval(`
subpkg.PrintA()
subpkg.PrintB()
`)
	if err != nil {
		panic(err)
	}
}
```

**Comment by mpl** [comment] 2020-07-16 13:22
Not marking as a bug yet, because I believe one (likely) way of solving this issue might be to redefine the API, and in particular the contract of Eval itself.

**Comment by mpl** [comment] 2020-07-20 13:58
@dfilipovic39 we're working on a solution for the regression, but something about what you said still puzzles me: If I go back far enough in the git history (eb25c84797ca95b3187ef0a15ada6ebe68ca129b), to avoid the regression, then sure enough, the second Eval does not fail anymore. However, the third Eval fails as so:
`panic: undefined selector: subpkg.PrintB`

So it seems to me there would be another problem anyway that would prevent this kind of use case, and yet you claim it used to work for you. Are you certain about that? If yes, do you know when (in the history of the project)? Or maybe you're thinking of a slightly different case? If yes, I would be interested in knowing about it.

**Comment by mpl** [comment] 2020-10-27 14:37
I think we can close this issue, as we consider Eval to work as intended for now, i.e. all Eval calls are supposed to be for the same "file-scope", within which there should not be any redeclaration (e.g. of imports).
In other words, if one wants to eval several scripts which should be considered in different scopes, then each script should be in a file, and one should use EvalPath.

And if we do want to revisit that approach, I think one elegant solution would be one evoked by #906 , i.e. EvalPath would support not only actual files, but rather file system implementations. Then script1 and script2 could be files in that broader file system sense.

WDYAT?

**Comment by dfilipovic39** [comment] 2020-10-28 19:06
Hi, just found interp_test.TestMultiEval and it seems it might be ok that way, need to check it with my real scripts but in isolated test case works ok. 
Running `interpreter.EvalPath("./my_pkg_dir")` does not work as expected tough, but opening each file by file in `my_pkg_dir`  manually and running `interpreter.EvalPath` for each of them works fine.

**Closed** 2020-10-30 15:10 UTC
Labels: area/core, bug

**Comment by james-lawrence** [comment] 2021-02-17 14:28
EvalPath has some other issues vs Eval. its not a equivalent work around particularly when dealing with go mod environments.
for example switching to EvalPath in the same directory prior to upgrade using a temp file generates:
`error: package location /path/to/package/foo not in GOPATH``

while inserting this snippet into yaegi resolves the issue with a random ID for the evaluated source.
```golang
func (interp *Interpreter) Eval2(name, src string) (res reflect.Value, err error) {
	return interp.eval(src, name, true)
}
```

providing a way at the API level to control the unique name would be a better option if you're going to rely on it internally for making decisions about the context.
