### ISSUE TITLE
Assigning a string as a map entry assigns interp.valueInterface instead

### ISSUE THREAD

**Issue by kabukky** [traefik/yaegi#327] opened 2019-08-07 07:11 UTC
The following program prints `fooValue type: interp.valueInterface` but I would expect `fooValue type: string`:

```go
package main

import (
	"fmt"
	"github.com/containous/yaegi/interp"
)

const src = `
func SetFooValue(m map[string]interface{}) { 
	m["foo"] = "bar"
}`

func main() {
	i := interp.New(interp.Options{})

	_, err := i.Eval(src)
	if err != nil {
		panic(err)
	}

	v, err := i.Eval("SetFooValue")
	if err != nil {
		panic(err)
	}

	setFooValue := v.Interface().(func(map[string]interface{}))
	testMap := make(map[string]interface{})
	setFooValue(testMap)

	fmt.Printf("fooValue type: %T\n", testMap["foo"])
}
```

Playground link: https://play.golang.org/p/9jTEu-hwgNQ

Expected result:
```console
fooValue type: string
```

But got:
```console
fooValue type: interp.valueInterface
```

Is this expected? If so, how would one go about assigning anything else than a `interp.valueInterface`?

**Comment by mvertes** [comment] 2019-08-07 16:26
This behaviour is normal, as  `interp.valueInterface` is the internal interpreter representation of aGo regular `interface{}` type. Within the interpreter context, it remains consistent, and you should be able to perform all the operations you desire *inside the script*. 

More work may be required when objects are handled both in compiled code and interpreted mode, and involve interface wrappers which need to be described properly in the doc.

**Comment by kabukky** [comment] 2019-08-08 06:23
@mvertes Thanks, that makes sense.
Supporting this would definitely create a lot more use cases for yaegi, so please consider it.

In the meantime I'm using a workaround by defining a compiled helper function that sets a value on a map:

```go
package main

import (
	"fmt"
	"github.com/containous/yaegi/interp"
	"reflect"
)

const src = `
import "helpers"
func SetFooValue(m map[string]interface{}) { 
	helpers.MapSet(m, "foo", "bar")
}`

var (
	helpers = interp.Exports{
		"helpers": map[string]reflect.Value{
			"MapSet": reflect.ValueOf(func(m map[string]interface{}, key string, value interface{}) {
				m[key] = value
			}),
		},
	}
)

func main() {
	i := interp.New(interp.Options{})

	i.Use(helpers)

	_, err := i.Eval(src)
	if err != nil {
		panic(err)
	}

	v, err := i.Eval("SetFooValue")
	if err != nil {
		panic(err)
	}

	setFooValue := v.Interface().(func(map[string]interface{}))
	testMap := make(map[string]interface{})
	setFooValue(testMap)

	fmt.Printf("fooValue type: %T\n", testMap["foo"])
}
```

Playground link: https://play.golang.org/p/ZlzKptb36AM

**Comment by mvertes** [comment] 2020-10-15 11:42
Closing it, as the issue is solved.

However there is an on-going effort to improve inter-operation between the executable and the interpreter and facilitate this kind of use case.

**Closed by mvertes** 2020-10-15 11:42 UTC
Labels: area/core
